#! /bin/sh
/usr/bin/apt-transport-i2p --littleboss=status 2>/dev/null || \
    nohup /usr/bin/apt-transport-i2p --littleboss=start & exit
/usr/bin/apt-transport-i2p --littleboss=status 2>/dev/null && \
    /usr/bin/apt-transport-i2p $@ &
